OUTPUT = "/data1/cgl/tasks/coco_box"

[TRAIN]
DEVICE = "cuda:0"
EPOCHES = 50
LOG_PER_PERIOD = 1000
CHECKPOINT_PER_EPOCHES = 1
PARALLEL_DEVICES = [0, 1]

[INPUT]
MIN_SIZE_TRAIN = 800
MAX_SIZE_TRAIN = 1000
MIN_SIZE_TEST = 800
MAX_SIZE_TEST = 1000
PIXEL_MEAN = [0.485, 0.456, 0.406]
PIXEL_STD = [0.229, 0.224, 0.225]

[DATA]
IMAGE_DIR = '/data1/cgl/dataset/coco2017/train2017'
ANN_FILE = '/data1/cgl/dataset/coco2017/annotations/instances_train2017.json'
BATCH_SIZE = 4
NUM_WORKERS = 10
SIZE_DIVISIBLE = 32

[MODEL]
CLS_AGNOSTIC_BBOX_REG = false

    [MODEL.FPN]
        IN_CHANNELS_LIST = [64, 256, 512, 1024, 2048]
        OUT_CHANNELS = 256

    [MODEL.RPN]
        ANCHORS_STRIDES = [4, 8, 16, 32, 64]
        ANCHORS_SIZES = [32, 64, 128, 256, 512]
        ANCHORS_RATIOS = [0.5, 1.0, 2.0]
        PRE_TOP_K_TRAIN = 2000
        POST_NMS_TOP_N_TRAIN = 2000
        FPN_POST_NMS_TOP_N_TRAIN = 2000
        PRE_TOP_K_TEST = 1000
        POST_NMS_TOP_N_TEST = 1000
        FPN_POST_NMS_TOP_N_TEST = 1000
        NMS_THRESHOLD = 0.7
        MIN_SIZE = 0
        FPN_POST_NMS_PER_BATCH = true
        FG_IOU_THRESHOLD = 0.7
        BG_IOU_THRESHOLD = 0.3
        BATCH_SIZE_PER_IMAGE = 256
        POSITIVE_FRACTION = 0.5
    
    [MODEL.ROI_HEADS]
        FG_IOU_THRESHOLD = 0.5
        BG_IOU_THRESHOLD = 0.5
        BBOX_REG_WEIGHTS = [10.0, 10.0, 5.0, 5.0]
        BATCH_SIZE_PER_IMAGE = 512
        POSITIVE_FRACTION = 0.25
        SCORE_THRESHOLD = 0.85
        NMS = 0.5
        DETECTIONS_PER_IMG = 100
        
    [MODEL.ROI_BOX_HEAD]
        POOLER_RESOLUTION = 7
        POOLER_SCALES = [0.25, 0.125, 0.0625, 0.03125]
        POOLER_SAMPLING_RATIO = 2
        MLP_HEAD_DIM = 1024
        USE_GN = false
        NUM_CLASSES = 81

[SOLVER]
BASE_LR = 0.0005
MOMENTUM = 0.9
MILESTONES = [10, 20, 30, 40]
WEIGHT_DECAY = 0.0005
GAMMA = 0.1

