[DATA]
IMAGE_DIR = '/data1/cgl/dataset/coco2017/val2017'
ANN_FILE = '/data1/cgl/dataset/coco2017/annotations/instances_val2017.json'
MIN_SIZE = 800
MAX_SIZE = 1000
BATCH_SIZE = 8
NUM_WORKERS = 10
SIZE_DIVISIBLE = 32

[MODEL]
    [MODEL.FPN]
        IN_CHANNELS_LIST = [64, 256, 512, 1024, 2048]
        OUT_CHANNELS = 256

    [MODEL.RPN]
        ANCHORS_STRIDES = [4, 8, 16, 32, 64]
        ANCHORS_SIZES = [32, 64, 128, 256, 512]
        ANCHORS_RATIOS = [0.5, 1.0, 2.0]