[DATA]
IMAGE_DIR_TRAIN = '/data1/cgl/dataset/coco2017/train2017'
ANN_FILE_TRAIN = '/data1/cgl/dataset/coco2017/annotations/instances_train2017.json'
IMAGE_DIR_VAL = '/data1/cgl/dataset/coco2017/val2017'
ANN_FILE_VAL = '/data1/cgl/dataset/coco2017/annotations/instances_val2017.json'
IMAGE_SIZE = 416
BATCH_SIZE_TRAIN = 8
BATCH_SIZE_VAL = 8

[MODEL]
DARKENT53_WEIGTH_PATH = '/data1/cgl/weights/yolov3/model_best.pth.tar'
NUM_BOXES = 3
NUM_CLASSES = 80
ANCHORS = [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]]
SCALES = [8, 16, 32]
HARD_THRESHOLD = 0.25