OUTPUT = "/data1/cgl/tasks/coco_box/yolov3"

[DATA]
IMAGE_DIR_TRAIN = '/data1/cgl/dataset/coco2017/train2017'
ANN_FILE_TRAIN = '/data1/cgl/dataset/coco2017/annotations/instances_train2017.json'
IMAGE_DIR_VAL = '/data1/cgl/dataset/coco2017/val2017'
ANN_FILE_VAL = '/data1/cgl/dataset/coco2017/annotations/instances_val2017.json'
IMAGE_SIZE = 416
BATCH_SIZE_TRAIN = 32
BATCH_SIZE_VAL = 32
MEAN = [0.485, 0.456, 0.406]
STD = [0.229, 0.224, 0.225]

[MODEL]
DARKENT53_WEIGTH_PATH = '/data1/cgl/weights/yolov3/darknet.pth.tar'
NUM_BOXES = 3
NUM_CLASSES = 80
ANCHORS = [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]]
SCALES = [8, 16, 32]

[LOSS]
NOOBJ_THRESHOLD = 0.5
LAMBDA_COORD = 1.0
LAMBDA_CLASS = 1.0
LAMBDA_OBJ = 1.0
LAMBDA_NOOBJ = 1.0

[TRAIN]
DEVICE = "cuda:1"
START_ITER = 0
NUM_ITERS = 30000
LOG_PER_ITERS = 100
CHECKPOINT_PER_ITERS = 1000
PRETRAINED_WEIGHTS_PATH = ""

    [TRAIN.OPTIMIZER]
    BASE_LR = 0.001
    MOMENTUM = 0.9
    WEIGHT_DECAY = 0.0005

    [TRAIN.SCHEDULER]
    STEP_SIZE = 100
    GAMMA = 0.98